env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ["plugin:react/recommended"]

parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  ecmaVersion: 6
  sourceType: module

plugins: ["react", "prettier"]

settings:
  react:
    version: "17"
